### PR TITLE
Update to v1.0.0

### PR DESCRIPTION
**Pull request by xmnlab**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by xmnlab** [comment]
@sodre I was a bit confused about this package ..
the pipy package is pointing to a fork not the original package: https://github.com/wntrblm/flask-talisman
and the conda-forge package uses the pypi but it is pointing to the original project (google cloud platform)

the original project stopped in the version 0.7 .. but the fork is now in the version 1.0.0

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@conda-forge-admin, please rerender

**Comment by xmnlab** [comment]
@sodre this PR is ready for review. thank you so much

**Comment by ocefpaf** [comment]
The maintainer here is MIA. I'll merge this b/c we could use more folks maintaining this one. Thanks!

**Comment by xmnlab** [comment]
thanks @ocefpaf for the review!

**Pull request merged**
